### ISSUE TITLE
建议：能不能提供顶层显示的功能

### ISSUE THREAD

**Issue by Vash90** [coodesker/coodesker-desktop#114]
鼠标移到盒子上，盒子打开后，里面的内容是显示在 背面的，会被前面的 其他应用遮挡。
能不能有 顶层显示的 选项，让盒子打开后，内容是顶层显示。

**Comment by caesar440315** [comment]
https://www.stardock.com/products/fences4/images/screenshots/release/fences4_ss02.png

The new version of the fence provides this functionality.However, it is inconvenient because you have to press hold hot 

key.Like the Windows Start menu, it would be better to press the hot key and click the icon to disappear the window.
